### ISSUE TITLE
Packaging Request for Arch Linux AUR

### ISSUE THREAD

**Issue by timlag1305** [Enitoni/pulseshitter#12]
Would you be interested in packaging this for the AUR? If not, I could give it a try and mirror the PKGBUILD in a public repository if you'd like.

**Comment by Enitoni** [comment]
I'm not quite sure how packaging for the AUR works, but I'd be happy to try, if it's not too much of a hassle.

**Comment by timlag1305** [comment]
It's been added. https://aur.archlinux.org/packages/pulseshitter
