### ISSUE TITLE
Add status that shows the name of the current stream

### ISSUE THREAD

**Issue by Emik03** [Enitoni/pulseshitter#14]
It would be neat if the bot changed its status according to the current name of the application that you are streaming, something along the lines of...

![image](https://github.com/Enitoni/pulseshitter/assets/14614115/5c9544e8-5767-4f0c-9235-f7eea0f47aa3)

**Comment by Enitoni** [comment]
Implemented in [v3.0.0.](https://github.com/Enitoni/pulseshitter/releases/tag/v3.0.0)
