### ISSUE TITLE
PulseAudio 15 compatibility

### ISSUE THREAD

**Issue by oatmealine** [Enitoni/pulseshitter#16]
[Void Linux currently does not have PulseAudio 16](https://github.com/void-linux/void-packages/tree/master/srcpkgs/pulseaudio), which seems to not like the flag `--format=json`:

```
λ pactl --format=json list sink-inputs
pactl: unrecognized option '--format=json'
```

causing the following error:

```
λ pulseshitter
thread 'main' panicked at 'parses pactl output: Error("EOF while parsing a value", line: 1, column: 0)', src/audio/pulse.rs:645:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Compatibility with 15 would be highly appreciated, as I currently have no way of upgrading it (PulseAudio binaries have a dependency on systemd, which Void Linux does not have) (there is a [closed (??) pull request](https://github.com/void-linux/void-packages/pull/39120) to update PulseAudio to 16. I do not know why it was closed)

**Comment by Enitoni** [comment]
This seems to me to be a responsibility held by Void Linux rather than pulseshitter. It is weird that the issue is closed without consideration or reason.

In any case, parsing the non-JSON output is not the easiest task and not one of my priorities at the moment, but if you really want this you are welcome to make a pull request.

**Comment by Enitoni** [comment]
Pardon the random events, I'm great at using GitHub. Haha.

**Comment by oatmealine** [comment]
Fair enough - I'm not the most familiar with Rust myself, but I might poke around a bit. Thank you for the response regardless!

**Comment by xAlpharax** [comment]
I shall add that Void currently has a recemtly open PR with the bump: https://github.com/void-linux/void-packages/pull/45249

**Comment by xAlpharax** [comment]
> [Void Linux currently does not have PulseAudio 16](https://github.com/void-linux/void-packages/tree/master/srcpkgs/pulseaudio), which seems to not like the flag `--format=json`:
> 
> ```
> λ pactl --format=json list sink-inputs
> pactl: unrecognized option '--format=json'
> ```
> 
> causing the following error:
> 
> ```
> λ pulseshitter
> thread 'main' panicked at 'parses pactl output: Error("EOF while parsing a value", line: 1, column: 0)', src/audio/pulse.rs:645:69
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> Compatibility with 15 would be highly appreciated, as I currently have no way of upgrading it (PulseAudio binaries have a dependency on systemd, which Void Linux does not have) (there is a [closed (??) pull request](https://github.com/void-linux/void-packages/pull/39120) to update PulseAudio to 16. I do not know why it was closed)

It has been updated finally :DD so this can be closed pretty much
