### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by jkbbwr** [Enitoni/pulseshitter#22]
Just wanted to say thanks for this project, everything else I tried was useless or required unsafe/insecure workarounds. 

![Thanks](https://media0.giphy.com/media/GCvktC0KFy9l6/giphy.gif?cid=ecf05e47pzfxusqs4ak4oofpn8ez30uuy54h8thjpevnjwnx&ep=v1_gifs_search&rid=giphy.gif&ct=g)

**Comment by Emik03** [comment]
maybe give this button a little push? o:
![image](https://github.com/Enitoni/pulseshitter/assets/14614115/26e49ab8-1400-4970-a2aa-9f7ca21c3a4c)

**Comment by jkbbwr** [comment]
Resolved
