### ISSUE TITLE
Any way to reconfigure for a new bot?

### ISSUE THREAD

**Issue by tactiical** [Enitoni/pulseshitter#24]
~~I was testing this on my alt account but I'd like to set it up again with my main and can't figure out how to do that~~

edit: nevermind, i found the config file

**Comment by Enitoni** [comment]
Yeah at the moment there's not a way to do this from within pulseshitter itself. The config file is stored in `$XDG_CONFIG_HOME` or `$HOME/.config` with a ron file called `pulseshitter-config.ron`

I was actually working on a refactor of the UI, then I got distracted with other work. But with said refactor, I planned to make it easier to change the config, and even adding settings to make it work how you want to.

I'm not sure when I will be able to work on this again, but I will leave the issue open until then.

**Comment by tactiical** [comment]
> Yeah at the moment there's not a way to do this from within pulseshitter itself. The config file is stored in `$XDG_CONFIG_HOME` or `$HOME/.config` with a ron file called `pulseshitter-config.ron`
> 
> I was actually working on a refactor of the UI, then I got distracted with other work. But with said refactor, I planned to make it easier to change the config, and even adding settings to make it work how you want to.
> 
> I'm not sure when I will be able to work on this again, but I will leave the issue open until then.

no worries, thank you for the reply!

**Comment by Enitoni** [comment]
This has now been implemented in [v3.0.0](https://github.com/Enitoni/pulseshitter/releases/tag/v3.0.0)! You no longer have to find the config file and edit it manually.
