### ISSUE TITLE
Latency and Time elapsed not working

### ISSUE THREAD

**Issue by FQQD** [Enitoni/pulseshitter#9]
It doesn't make this nice script unusable, but still butgs me out. the Latency and Time display in the Audio section of the CLI don't seem to chnage, at all. Otherwise, this works perfectly fine.
![image](https://user-images.githubusercontent.com/96952506/235157781-f4fa042b-33c5-4f58-bd4e-7060bbc8cad7.png)

CPU: quad core AMD Ryzen 3 3200G with Radeon Vega Graphics (-MCP-)
speed/min/max: 2862/1400/3600 MHz Kernel: 6.2.12-1-cachyos-tt x86_64 Up: 47m
Mem: 3947.3/15921.6 MiB (24.8%) Storage: 2.38 TiB (11.5% used) Procs: 269
Shell: fish inxi: 3.3.26

**Comment by Enitoni** [comment]
Hmm, is this while the audio is playing? Due to a limitation that I cannot seem to figure out, when parec is not transmitting audio, the meter and this timer will freeze.

**Comment by FQQD** [comment]
yes, it's also while playing music. it doesnt change at all.

**Comment by Enitoni** [comment]
What audio device are you using? I'm guessing the audio device may play a part of why parec is not reporting the time.

**Comment by FQQD** [comment]
I'm unsure what you mean by that, but I'm using a Behringer Xenyx 302USB as my audio device. As seen in the screenshot, it seems to use the PCM2902 Chipset. (I'm unsure though)

**Comment by Enitoni** [comment]
Hm, okay. Can you try running the parec command in your terminal that pulseshitter is running? You can find it by using a process manager such as htop. Then copy the command, let it run for a bit (with your audio source playing audio) and then send me what it logged.

**Comment by FQQD** [comment]
I think my computer is just screaming at me.
This was my command:
`parec --verbose --device alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo-output.monitor --monitor-stream 168 --format=float32le --rate=48000 --channels=2 --latency=1 --process-time=1`

This is what "logged":

https://user-images.githubusercontent.com/96952506/235436800-2efc7027-579f-440d-ac97-1d45dd87faec.mp4


I tried it once without and with pulseshitter running.

**Comment by Enitoni** [comment]
Ah, my bad. I forgot it will pipe the actual audio into your stdout. Try running it with `>/dev/null` at the end.

**Comment by FQQD** [comment]
okay, it works fine in the log. i think both the time and the latency is correct.

https://user-images.githubusercontent.com/96952506/235949748-dcde4f4e-483a-45b5-980c-934eddafff42.mp4

**Comment by Enitoni** [comment]
Okay yeah, so my suspicions were right. You have a locale on your system that changes the delimiter in `Time` to a comma. But pulseshitter expects that to be a period. I think this is similar to https://github.com/Enitoni/pulseshitter/issues/7

Could you try setting the environment variable (mentioned in that issue) and seeing if that changes the delimiter to a period?

**Comment by FQQD** [comment]
![image](https://user-images.githubusercontent.com/96952506/236243455-c597c56b-3302-46be-9d19-3f9a9093f361.png)
ah. it works. is it possible for you to make it compatible with other locales or something? otherwise, i'll just run with the fix.

**Comment by Enitoni** [comment]
Fixed by https://github.com/Enitoni/pulseshitter/commit/06670f9beee363f052cc5011413fb92b7ca82dc4
